### ISSUE TITLE
vue项目打包后丢失地图

### ISSUE THREAD

**Issue by Steven201612** [plainheart/echarts-extension-amap#11]
我在vue-cli3项目本地编译可以加载地图，但打包后地图不能加载，跟我在本地注释调echarts-extension-amap的效果一样，呈现空白

**Comment by plainheart** [comment]
是否有什么错误信或者例子息可以提供？以方便测试定位下问题，谢谢。

**Comment by plainheart** [comment]
@Steven201612  可能是由于打包问题，我已经发布了一个新版本 1.6.0 到NPM，你可以更新依赖包再试一下，谢谢！

**Comment by Steven201612** [comment]
好的，感谢

发自我的iPhone

**Comment by xiangshu233** [comment]
问一下BUG修复了吗，正准备应用到线上

**Comment by plainheart** [comment]
@xiangshu233 应该修复了。最近也修改了一些其他问题，还没发版。可以等晚上 1.8.0 发版之后，使用最新版。

**Comment by plainheart** [comment]
@xiangshu233 Hi, 1.8.0 已发版。
NPM：https://www.npmjs.com/package/echarts-extension-amap/v/1.8.0
jsDelivr CDN: https://www.jsdelivr.com/package/npm/echarts-extension-amap?version=1.8.0

**Comment by xiangshu233** [comment]
你好，我npm下载的如果更新的话卸载重新安装就可以了吧

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Zhongxiang.Wang<mailto:notifications@github.com>
发送时间: 2021年1月12日 19:40
收件人: plainheart/echarts-extension-amap<mailto:echarts-extension-amap@noreply.github.com>
抄送: 傲慢或香橙<mailto:xiangshu233@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [plainheart/echarts-extension-amap] vue项目打包后丢失地图 (#11)


@xiangshu233<https://github.com/xiangshu233> Hi, 1.8.0 已发版。
NPM：https://www.npmjs.com/package/echarts-extension-amap/v/1.8.0
jsDelivr CDN: https://www.jsdelivr.com/package/npm/echarts-extension-amap?version=1.8.0

―

**Comment by plainheart** [comment]
@xiangshu233 不用特意卸载，重新执行 `npm i echarts-extension-amap@1.8.0 -S` 即可。

**Comment by xiangshu233** [comment]
好的，谢谢您

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Zhongxiang.Wang<mailto:notifications@github.com>
发送时间: 2021年1月14日 9:17
收件人: plainheart/echarts-extension-amap<mailto:echarts-extension-amap@noreply.github.com>
抄送: 傲慢或香橙<mailto:xiangshu233@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [plainheart/echarts-extension-amap] vue项目打包后丢失地图 (#11)


@xiangshu233<https://github.com/xiangshu233> 不用特意卸载，重新执行 npm i echarts-extension-amap@1.8.0 -S 即可。

―

**Comment by SKII-SU** [comment]
我也出现可这个问题，本地可以展示地图打包后展示不了，版本是v1.9.3

**Comment by plainheart** [comment]
@SKII-SU 能否麻烦你抽空提供一个最小化 demo？

**Comment by SKII-SU** [comment]
@plainheart 换成1.8.0的版本问题解决了

**Comment by plainheart** [comment]
@SKII-SU 好的，不过我还是希望能够提供一下，方便测试找出 1.9.3 无法显示的原因。

**Comment by SKII-SU** [comment]
@plainheart  应该是一开始引入出错了，包删掉后换成cdn引入没有问题了（最新版本）

**Comment by BraisedChicken** [comment]
@plainheart 我也碰到了类似的问题，发现使用import引入就会有这个问题，改用require就没有问题了。
项目因为是和国企合作没法提供DEMO，抱歉没法帮上忙。

**Comment by plainheart** [comment]
参见 #18，应该是一样问题，最新版 v1.9.5 应该已解决该问题。
