### ISSUE TITLE
如何地图之上创建一个geojson的地图轮廓

### ISSUE THREAD

**Issue by zhengquan45** [plainheart/echarts-extension-amap#15]
如何地图之上创建一个geojson的地图轮廓。我尝试性的在echart的option配置添加了 series: [
                    {
                      name: 'PM2.5',
                      type: "map",
                      mapType: 'SHAOWU', // 自定义扩展图表类型
                      // 使用高德地图坐标系
                      coordinateSystem: "amap",
}
SHAOWU是我自定义的县市的地图,发现无法生效，是不支持吗？
https://github.com/zhengquan45/shaowu

补充：我发现这个插件是建立在geo基础上的 也就是说geo这种地图坐标系所支持的图标绘制好像只有热力 气泡 散点 线型这四种 其他则无法支持，是这样吗

**Comment by plainheart** [comment]
`map` 需要 `geo` 坐标系支持。
`amap` 坐标系 和 `geo` 坐标系算是平行的两个概念，暂时无法在 `amap` 坐标系上添加 `map` 系列。

**Comment by plainheart** [comment]
可以考虑利用高德地图自带的 [`geoJSON`](https://lbs.amap.com/api/javascript-api/reference/overlay#geojson) 去绘制。
