### ISSUE TITLE
ionic项目，使用prod，release打包ios后报错getComponent("amap") undefined

### ISSUE THREAD

**Issue by sip07** [plainheart/echarts-extension-amap#18]
使用版本：    "echarts-extension-amap": "^1.9.1",
报错：
![image](https://user-images.githubusercontent.com/42925326/111583824-eeeb4500-87f7-11eb-9d08-8b62460b430a.png)
在localstorage中查看发现只加载了一部分
![image](https://user-images.githubusercontent.com/42925326/111584083-5c977100-87f8-11eb-8795-0290e9578205.png)

使用：
![image](https://user-images.githubusercontent.com/42925326/111583695-bf3c3d00-87f7-11eb-9f2c-0e497753f115.png)

![image](https://user-images.githubusercontent.com/42925326/111583585-a92e7c80-87f7-11eb-8ffe-f72f57799fa1.png)

amap、echarts对象都可以获取的到，但是在setOption之后仍然获取amapComponent失败
在debug打包/safari调试时地图都可以正常显示

麻烦您帮忙看一下，实在是没有思路如何解决了🙏

在getmodel的componentMap中发现报了严格模式相关的错误，不知道是否是这个引起的问题
![image](https://user-images.githubusercontent.com/42925326/111590358-f82cdf80-8800-11eb-8906-3ce929255bc2.png)

**Comment by plainheart** [comment]
感觉像是 notMerge 的缘故，如果为 true，记得把 amap 的相关 option 也带上，不然可能会在 setOption 后被移除以至于获取不到。

**Comment by sip07** [comment]
> 感觉像是 notMerge 的缘故，如果为 true，记得把 amap 的相关 option 也带上，不然可能会在 setOption 后被移除以至于获取不到。

你好，感谢回复。
我尝试了将notmerge属性去掉，但仍然是无法显示
![image](https://user-images.githubusercontent.com/42925326/111603211-1699d780-880f-11eb-91cf-39a5e1ec2596.png)

**Comment by plainheart** [comment]
抱歉，从目前的信息来看，我暂时看不出问题所在。

**Comment by plainheart** [comment]
对了 能不能提供更多错误信息？

**Comment by sip07** [comment]
> 对了 能不能提供更多错误信息？

这就是所有我能找到的错误信息了，今天用prod模式在safari上调试了一下，看到报了这个错误
![image](https://user-images.githubusercontent.com/42925326/111748249-40183900-88cb-11eb-8493-d3e980a1733d.png)

**Comment by plainheart** [comment]
这看起来像是 echarts 没有引入？ `t` 实际上是 echarts
可以引入非压缩的 echarts-extension-amap.js 调试看看。

**Comment by sip07** [comment]
> 这看起来像是 echarts 没有引入？ `t` 实际上是 echarts
> 可以引入非压缩的 echarts-extension-amap.js 调试看看。
> 
> 另外建议用最新版 1.9.3 试一试，1.9.1 存在一个问题。

好的，谢谢，我周一试一下

**Comment by sip07** [comment]
你好，我试了一下，问题应该就是出在setOption之后amap没有被加载进echart的model中。
非prod情况下的getmodel：
![image](https://user-images.githubusercontent.com/42925326/112801264-42387f80-90a3-11eb-85ac-04e04865837b.png)
prod模式下的getmodel
![image](https://user-images.githubusercontent.com/42925326/112801332-5a100380-90a3-11eb-9c24-8bcfce6cce88.png)

**Comment by plainheart** [comment]
能否贴出 echarts 和 echarts-extension-amap 引入相关的代码？另外观察下 echarts.amap 是否有值。是不是在调用 echarts setOption 之前就已经抛出错误了？

**Comment by plainheart** [comment]
bmap 插件能正常运行吗？
amap-extension 现在改成了依赖  `echarts/lib/echarts` 而不是以前的 `echarts`。可能是这个原因导致的。

**Comment by sip07** [comment]
bmap是可以正常运行的，那天尝试了一下。
![image](https://user-images.githubusercontent.com/42925326/112969974-52725c80-9180-11eb-8ab3-947a276eb1bd.png)
![image](https://user-images.githubusercontent.com/42925326/112970180-80f03780-9180-11eb-9417-586c9ebb84b4.png)

我把js包里的依赖改了以后重新运行，但是还是不行

**Comment by plainheart** [comment]
对了，如果暂时找不出问题所在，我猜想既然 bmap 可以，那应该 amap 1.9.0 之前的版本也可以，你可以安装使用 [v1.8.0](https://github.com/plainheart/echarts-extension-amap/releases/tag/v1.8.0) 这个代码结构和 bmap 差不多，应该能正常工作。最后感谢你持续的反馈。

**Comment by sip07** [comment]
使用了1.8.0的版本现在可以正常显示了！谢谢！

**Comment by wuhuama** [comment]
vue项目
"echarts": "^4.7.0",
 "echarts-extension-amap": "^1.9.2",

prod环境跟上面这位情况一样
![image](https://user-images.githubusercontent.com/22308830/117598227-f4bb3200-b179-11eb-86e4-91542060159f.png)
![image](https://user-images.githubusercontent.com/22308830/117598265-0bfa1f80-b17a-11eb-840d-32cac2c5bb46.png)

**Comment by plainheart** [comment]
@wuhuama 也是 ionic 项目吗？说实话，能提供一个最简的能复现的例子会好很多...

**Comment by ErricLu** [comment]
我也是同样的问题，非ionic的项目，复现你可以按vue官方脚手架起一个工程，vue3.0 echarts5.0+版本，高德api v1的最新版，本地开发没问题，项目build后的代码会报getAmap的错误，错误如上

**Comment by plainheart** [comment]
@ErricLu 谢谢反馈！目前已定位到原因，稍后会更新修复下。

**Comment by plainheart** [comment]
已发 v1.9.4
