### ISSUE TITLE
数据量稍大，地图平移就不起作用，卡

### ISSUE THREAD

**Issue by ErricLu** [plainheart/echarts-extension-amap#19]
vue3.0 + echarts5.0 + 高德v2.0
1. 当effectScatter data数据量较少时，地图移动缩放都没问题，当数据量稍微大一点移动就不起作用。
2. 尝试将高德api换成v1.4.15版本后就没有这个问题

**Comment by ErricLu** [comment]
可以就用你事例代码scatter. html测试，将data中取六个改成concat叠加即可复现

**Comment by plainheart** [comment]
@ErricLu 

`effectScatter` 每帧都在重绘，不适合数据量太多的情况。另外高德地图 2.0 在移动时会比较频繁地触发移动事件，每回调一次则重绘一次 echarts，这应该是导致卡顿的原因。

可以考虑如下几种方案：
1、将 `effectScatter` 分在多个 series 中，而不是在同一个 `series` 里，并配置不同的 [`zlevel`](https://echarts.apache.org/zh/option.html#series-effectScatter.zlevel)，不过可能并不能优化太多。
2、设置 `renderOnMoving` 为 `false`，禁用实时渲染，等待拖拽完毕后再渲染。
3、开启 `largeMode`，不过可能拖拽体验上不是太好。
