### ISSUE TITLE
引入高德本来已经完成了，但最近出现获取不到地图实例的问题

### ISSUE THREAD

**Issue by SeanSunPeng** [plainheart/echarts-extension-amap#2]
![图片](https://user-images.githubusercontent.com/43394112/70693313-2ebfa480-1cf8-11ea-84f6-8136447acb98.png)
之前功能做好了，但最近又会失效，然后又好了，今天又坏了，是不是echarts-amp.min.js这个文件开始失效了，这么反复是什么问题

**Comment by plainheart** [comment]
可以贴出部分代码吗？方便定位下问题。
