### ISSUE TITLE
在配置项中设置x轴或y轴的样式报错

### ISSUE THREAD

**Issue by zengyuehao** [plainheart/echarts-extension-amap#22]
"TypeError: r.getAxesOnZeroOf is not a function"

**Comment by plainheart** [comment]
不支持直角坐标系

**Comment by zengyuehao** [comment]
> 不支持直角坐标系

感谢回复，我目前有个疑问，直接使用css的cursor无法改变鼠标样式，高德地图提供的setDefaultCursor在amap中配置没有效果，我该怎样使用setDefaultCursor呢？

**Comment by plainheart** [comment]
默认情况下，ECharts 图层 z-index 比高德地图图层大，是在其上方，高德地图的事件是不会响应的。如果需要高德地图响应鼠标事件，需要设置 `echartsLayerInteractive` 为 `false`，不过这会导致 ECharts 图层无法响应鼠标事件，两者只能其一。
