### ISSUE TITLE
关于监听缩放移动事件

### ISSUE THREAD

**Issue by CNFeffery** [plainheart/echarts-extension-amap#23]
在`geo`和`bmap`下可以使用事件`georoam`与`bmaproam`来监听地图缩放与拖拽移动事件下的参数，但是我试了`amaproam`只返回了这些信息：
![image](https://user-images.githubusercontent.com/49147660/121111573-b335a980-c841-11eb-82f3-5285672009a0.png)

是目前还没有针对更多参数监听例如缩放级别进行开发吗

**Comment by plainheart** [comment]
bmap 下的参数是怎样的？

**Comment by CNFeffery** [comment]
@plainheart 
对的，我发现直接用高德地图自带的事件监听就可以获取到了：
![image](https://user-images.githubusercontent.com/49147660/121131118-ebe57b00-c861-11eb-8918-54b901cb4764.png)
![image](https://user-images.githubusercontent.com/49147660/121131166-f6077980-c861-11eb-8c74-d1d46d4f2ff5.png)

**Comment by plainheart** [comment]
你需要 amaproam 能直接监听获取这些参数吗？

**Comment by CNFeffery** [comment]
@plainheart 
如果能对常见的缩放级别、当前地图矩形坐标范围等按照echarts的方式进行监听会方便很多，现在虽然也可以获取到，但是要麻烦一些

**Comment by plainheart** [comment]
已发 [v1.10.0](https://github.com/plainheart/echarts-extension-amap/releases/tag/v1.10.0)

新增 `returnMapCameraState` 配置项，设置为 `true` 监听 `amaproam` 事件将能获取到地图相机状态，如中心点、缩放级别、俯仰角度、地图范围等信息。

参见示例：https://codepen.io/plainheart/pen/qBbdNYx
