### ISSUE TITLE
高德地图Marker对象的事件无法触发。

### ISSUE THREAD

**Issue by BraisedChicken** [plainheart/echarts-extension-amap#28]
echarts: v5.1.2
echarts-extension-amap: v1.10.0
AMap:v1.4.15

正常使用高德地图时，Marker实例绘制的DOM节点，层级高于图层，可以在浏览器中被检查器直接选中。使用echarts结合地图使用时，Maker实例的DOM节点被覆盖导致事件无法触发。

**Comment by plainheart** [comment]
可以设置 `echartsLayerInteractive` 为 `false`。这样 ECharts 图层将不会触发鼠标事件。
