### ISSUE TITLE
这个问题当中 使用v1.8.0打包后能够加载 但是使用后续版本还是无法正确加载地图 使用1.8.0会有一个echart层和地图层有偏移的问题 但是后续版本又无法打包

### ISSUE THREAD

**Issue by cacccc** [plainheart/echarts-extension-amap#30]

**Comment by plainheart** [comment]
我这里试了下是可以正常打包运行的，参见下方附件。
[vue-echarts-extension-amap.zip](https://github.com/plainheart/echarts-extension-amap/files/7104898/vue-echarts-extension-amap.zip)


不过，借你反馈发现一个运行时 bug，目前的代码导致只能在加载完高德地图之后才能 import 插件，还好影响不算太大。
下个版本会修改下。

**Comment by cacccc** [comment]
> 我这里试了下是可以正常打包运行的，参见下方附件。
> [vue-echarts-extension-amap.zip](https://github.com/plainheart/echarts-extension-amap/files/7104898/vue-echarts-extension-amap.zip)
> 
> 不过，借你反馈发现一个运行时 bug，目前的代码导致只能在加载完高德地图之后才能 import 插件，还好影响不算太大。
> 下个版本会修改下。
> 
> **UPDATE**
> 已发 1.10.1

感谢大佬的代码   我之前echarts版本是4.9  升级之后就没有问题了

**Comment by plainheart** [comment]
可能跟你的项目配置以及引入 echarts 的方式有关，我使用 4.9.0 也可以正常打包构建。
