### ISSUE TITLE
散点图，数量达到3500个点以上就会出现卡顿

### ISSUE THREAD

**Issue by yi-boide** [plainheart/echarts-extension-amap#32]
散点图，数量达到3500个点以上就会出现卡顿，缩放，拖动卡顿感非常明显，请问有什么解决方法吗？
目前已经有10200个点了，我这后续需要渲染几万个点

**Comment by plainheart** [comment]
数据量大的话建议将 `renderOnMoving` 设置为 `false`，`largeMode` 设置为 `true` 看看会不会好些。因为默认只要地图视图发生变化，ECahrts 就会重绘一次，尤其是高德地图 2.0 用了 WebGL 这个重绘会更频繁。

另外，从 ECharts 方面，可以考虑试试 [渐进式渲染](https://echarts.apache.org/zh/option.html#series-scatter.progressive) 和 [大数据量优化](https://echarts.apache.org/zh/option.html#series-scatter.large)。如果其中有用涟漪散点图，建议配置下 [zlevel](https://echarts.apache.org/zh/option.html#series-effectScatter.zlevel) 使之与普通散点分层渲染。

**Comment by yi-boide** [comment]
将renderOnMoving设置为false，largeMode设置为看true后，拖动，缩放卡顿效果有了明显改观，不过将鼠标移入到点上面时的label提示还是不会展示出来，label的提示是否可以改为点击才展示提示？

**Comment by plainheart** [comment]
label 可能不太行，不过 tooltip 可以，设置 [`tooltip.triggerOn`](https://echarts.apache.org/zh/option.html#tooltip.triggerOn) 为 `click` 即可。

**Comment by yi-boide** [comment]
我这个点是有1000多组series组成的10200个点，每个series中点的数量不定，点的提示做到tooltip中，不使用label是吧

**Comment by plainheart** [comment]
提示如果复杂的话建议用 tooltip，如果比较简单，就显示个名字的话，label 足够了。

> 点的大小能够随着缩放的变化而改变吗

ECharts 暂不支持根据比例缩放。不过可以尝试自己实现，思路是监听地图的 `zoomchange` 事件，计算一个你认为合适的比例，用 setOption 更新下 symbolSize 即可。

**Comment by yi-boide** [comment]
非常感谢，根据你提供的方法，已解决卡顿问题。
