### ISSUE TITLE
关于速度

### ISSUE THREAD

**Issue by schzh** [plainheart/echarts-extension-amap#33]
Amap加载地图偏慢，哪怕已经加载过，瓦片之类的在缓冲文件夹都有缓存，加载加载还是慢，请问是否有什么方法可以改进下？

**Comment by plainheart** [comment]
是引入了本插件之后加载变慢还是仅仅使用高德地图就很慢？

**Comment by schzh** [comment]
感觉是这个插件加载高德地图慢？

**Comment by plainheart** [comment]
拿 README 中提供的例子来说，我这里加载很快啊...

**Comment by schzh** [comment]
仔细分辨下，是3D慢。2D还是挺快的

**Comment by plainheart** [comment]
应该不是高德地图的问题... 你有在用 CDN 吗？示例用的是 jsDelivr CDN，因为近期他们失去了国内的 ICP 备案，来自大陆的流量都会被转发到临近大陆的节点，可能会有日本、美国等，导致速度变慢甚至打不开的情况。
