### ISSUE TITLE
有匹配高德API 2.0的计划吗？

### ISSUE THREAD

**Issue by schzh** [plainheart/echarts-extension-amap#34]
看示例都是匹配高德API 1.4.15，有匹配高德API2.0的计划吗？据说2.0改进还是比较大的。
直接引用试过，原来1.4.15正常的句子，2.0就出错了。
例如var opts={subdistrict:0,extensions:'base',level:'city'};var district=new AMap.DistrictSearch(opts);
这句在2.0下报错：对象不支持assign属性或方法
1.4.15正常，不通过这个模块直接使用高德API也正常

**Comment by plainheart** [comment]
从一开始都支持 2.0。高的这个区域搜索 `DistrictSearch` 需要单独引入插件，参考[官方文档](https://lbs.amap.com/api/javascript-api/guide/services/district-search/#:~:text=%E4%BD%BF%E7%94%A8%E8%A1%8C%E6%94%BF%E5%8C%BA%E5%88%92%E6%9F%A5%E8%AF%A2%E6%9C%8D%E5%8A%A1%E5%89%8D%E8%A6%81%E5%85%88%E5%BC%95%E5%85%A5%E8%AF%A5%E6%8F%92%E4%BB%B6%EF%BC%8C%E5%85%B7%E4%BD%93%E7%9A%84%E5%BC%95%E5%85%A5%E6%96%B9%E5%BC%8F%E8%AF%B7%E5%8F%82%E8%80%83%E6%95%99%E7%A8%8B%EF%BC%9A%E6%8F%92%E4%BB%B6%E7%9A%84%E4%BD%BF%E7%94%A8%E3%80%82)。

**Comment by schzh** [comment]
应该不是这个问题，因为开始用v=1.4.15的时候就在初始连接上用plugin=AMap.DistrictSearch参数引入了，一直也是正常的，现在只是v=1.4.15改成v=2.0，其他的任何地方都没改，就出错了

**Comment by plainheart** [comment]
我在示例基础上改成 2.0 使用此插件没有出现问题。如果可以，建议提供下能复现的示例，我具体看下。

**Comment by schzh** [comment]
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <title></title>
    <style>html,body,#container{margin:0;height:100%}</style>
</head>
<body>
<div id="charts1" style="height:100%;width:100%;position:absolute"></div>
<script src="echarts.js"></script>
<script src="echarts-extension-amap.min.js"></script>
<script type="text/javascript" src="https://webapi.amap.com/maps?v=2.0&key=your key&plugin=AMap.DistrictSearch"></script>
<script type="text/javascript">
var district = null;
var polygons=[];
if(!district){
    var opts = {subdistrict: 0,extensions: 'all', level: 'district'};
    district = new AMap.DistrictSearch(opts);}
option = {
  amap: {viewMode: '3D',center: [108.39, 39.9],zoom: 4},
  series: [{type: 'scatter',coordinateSystem: 'amap',data: [[120, 30, 8], [120.1, 30.2, 20]],encode: {value: 2}}]
};
var chart1=document.getElementById('charts1');echarts.dispose(chart1);chart=echarts.init(chart1);chart.setOption(option,true);
</script>
</body>
</html>

**Comment by schzh** [comment]
其实就是你的那个示例+他的那个示例的两句。那个2.0换成1.4.15则没有任何问题

**Comment by schzh** [comment]
IE11的错误是：SCRIPT438: 对象不支持“assign”属性或方法
eval code (60) (1,1318)

Chrome的错误是：maps?v=2.0&key=&plugin=AMap.DistrictSearch:1 Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at HTMLIFrameElement.t.onload (https://webapi.amap.com/maps?v=2.0&key=  &plugin=AMap.DistrictSearch:1:501896)

**Comment by plainheart** [comment]
IE 这个应该是语法兼容性问题 不支持 Object.assign 函数 可以自行添加或者引入三方 polyfill 解决。另外高德地图2.0用了 webgl 和 worker，对浏览器要求会高些。
Chrome 那个错误应该是因为是从本地文件直接打开的，缺失 origin，起一个 http server 去运行就不会报这个错误了。

**Comment by schzh** [comment]
> IE 这个应该是语法兼容性问题 不支持 Object.assign 函数 可以自行添加或者引入三方 polyfill 解决。另外高德地图2.0用了 webgl 和 worker，对浏览器要求会高些。 Chrome 那个错误应该是因为是从本地文件直接打开的，缺失 origin，起一个 http server 去运行就不会报这个错误了。

谢谢，Chrome 用 http server可以解决。
IE11引入polyfill确实可以解决不兼容Object.assign的问题，但是很快后面还是会出别的错误，例如
buildingLayer=new AMap.Buildings();amap.add(buildingLayer);
会出错：SCRIPT5007: 无法获取未定义或 null 引用的属性“Ha”
maps (1,545996)

**Comment by plainheart** [comment]
这应该是高德地图2.0的兼容性问题了。2.0对浏览器版本较高，IE 下有些插件如果他们官方没有作兼容处理的话，肯定会有这类问题。建议用 Edge 或 Firefox、Chrome 运行。一定要兼容IE的话，我想只能保持用1.4.15版的了。

**Comment by schzh** [comment]
> IE 这个应该是语法兼容性问题 不支持 Object.assign 函数 可以自行添加或者引入三方 polyfill 解决。另外高德地图2.0用了 webgl 和 worker，对浏览器要求会高些。 Chrome 那个错误应该是因为是从本地文件直接打开的，缺失 origin，起一个 http server 去运行就不会报这个错误了。

放弃兼容IE了，太繁琐，另外Chrome不使用http server也可以解决，只要加上参数"disable-web-security"，Chrome也可以打开本地的html文件不出跨域错误

**Comment by schzh** [comment]
另外有个问题请教下：

使用Amap绘制自定义图，使用一个amap的一个预设的zoom和center参数先绘制地图，然后根据大量数据数据点绘制自定义柱形图，绘制完毕，根据数据情况重设了一次边界。

然后后面增加一个点，因为增加的这个点不想再重新绘制所有原有点，所以使用了echarts1.setOption(opt2,{replaceMerge:'series[0].data'})的合并参数，预期是只绘制增加的这个点，其余不动。实际结果是确实可以只增加这个点，但是地图本身出问题了，在绘制结束后，地图自动重绘了，导致柱形图也跟着重绘。而且是使用的最早的那个amap的一个预设的zoom和center参数绘制的，忽略了后来程序设置的边界，以及手动的缩放和平移。

请教这个问题有办法解决吗？能否在柱形图增加一个点的时候，地图不重绘不回归初始的zoom和center？
