### ISSUE TITLE
如何解决在echarts 上拖拽同时地图一同拖拽

### ISSUE THREAD

**Issue by andyFang94** [plainheart/echarts-extension-amap#35]
如何解决在echarts 上拖拽同时地图一同拖拽？
请教下有没有人知道这块是如何实现的？

**Comment by plainheart** [comment]
现在不能拖拽吗？

**Comment by plainheart** [comment]
哦 貌似理解错了 你是不是希望拖拽 echarts 避免地图被拖拽？

**Comment by andyFang94** [comment]
> 哦 貌似理解错了 你是不是希望拖拽 echarts 避免地图被拖拽？ 我在 Google Map 扩展里回复过类似需求，参见 [plainheart/echarts-extension-gmap#5](https://github.com/plainheart/echarts-extension-gmap/issues/5)，后面会看下高德地图能不能处理。

hi, 感谢您的回复， 其实我目前在模仿 echarts-extension-amap  实现一个类似echarts-extension-bingmap 的东西
例如1：
bing map 为底
echarts  层级最上， 上画气泡图  滑动的时候 带动不了bing map （其实希望一同滑动）
例2：
bing map 在上  和 echats 在中，可实现拖动 但是没有echarts 的tooltips

**Comment by plainheart** [comment]
不太熟悉必应地图，不过原理都差不多，一般会用地图提供的自定义 overlay 或者 layer 将 ECharts 图层嵌入到地图中，一般都是在地图图层上方（当然也可以通过 z-index 调整层叠顺序，用于防止图表元素覆盖住地图本身的覆盖物的场景），然后监听地图的更新事件（如移动、缩放、倾斜、旋转等），重绘 ECharts 图层即可。

**Comment by andyFang94** [comment]
thx
