### ISSUE TITLE
切换按钮页面丢失

### ISSUE THREAD

**Issue by zhang-yong-qiang** [plainheart/echarts-extension-amap#36]
我设置了三个按钮，对应三个地图组件，默认加载第一个地图组件，当我第一次切换按钮时，加载对应的地图组件，当我再次点击第一个按钮时，就不加载地图组件了，地图组件没有了，丢失了，请问是什么原因。

**Comment by plainheart** [comment]
只看这段话我不太能搞清楚你具体是怎么做的，如果可以建议提供一个例子。
