### ISSUE TITLE
地图展示ecahrt 饼图，饼图位置一直在地图左上角

### ISSUE THREAD

**Issue by hulalalalala** [plainheart/echarts-extension-amap#38]
地图展示ecahrt 饼图，饼图位置一直在地图左上角，代码如下：
`{
          id: 'stationPie' + index,
          center: item.coord,
          color: ['#5ad4cf', '#ffd258'], // 饼图每个扇形的颜色
          coordinateSystem: 'amap',
          data: [
            { name:'上车人数', value: item.up },
            { name: '下车人数', value: item.down },
          ],
          itemStyle: {
            normal: {
              borderColor: '#ffffff',
              borderWidth: 0.3
            }
          },
          name: item.name,
          radius: '24px',
          type: 'pie',
          zlevel: 5
        }`

**Comment by plainheart** [comment]
感谢反馈。首先，目前 ECharts 的饼图的 `center` 只是屏幕坐标，无法识别具体的经纬度，所以你传入的 `item.coord` 会被当作屏幕坐标而显示在左上角。正确的写法应该是转换经纬度为具体的屏幕坐标，然后再赋值给饼图系列的 `center`。
参考示例：https://codepen.io/plainheart/pen/GRQNyoJ

**Comment by hulalalalala** [comment]
> 感谢反馈。首先，目前 ECharts 的饼图的 `center` 只是屏幕坐标，无法识别具体的经纬度，所以你传入的 `item.coord` 会被当作屏幕坐标而显示在左上角。正确的写法应该是转换经纬度为具体的屏幕坐标，然后再赋值给饼图系列的 `center`。 参考示例：https://codepen.io/plainheart/pen/GRQNyoJ

感谢作者回复，我最终就是按这个思路解决的。因为百度地图支持传经纬度，所以我才来问问滴。

**Comment by plainheart** [comment]
@hulalalalala 你确定百度地图扩展可以直接传经纬度而无需转换吗？这两个扩展的实现方式是类似的，理论上都是需要提前转换为像素坐标的。
