### ISSUE TITLE
引入自己的key和自定义地图主题无效

### ISSUE THREAD

**Issue by cyy-1314** [plainheart/echarts-extension-amap#46]
大神你好，想问一下是不是只支持官方的主题色呀，我确定自己用的key可Id是对应正确的，本地也可以出来我设置的地图，但是在您这边例子里改变不了地图主题，是否与高德地图后面出的规定有关？->(自2021年12月02日升级，升级之后所申请的 key 必须配备安全密钥 jscode 一起使用),我本地需要key和密钥搭配使用，地图才会生效。您这的代码里哪里可以调用密钥吗？谢谢解答

**Comment by plainheart** [comment]
调用密钥的方式和高德地图官方一致，和这个扩展没有关系。
