### ISSUE TITLE
高德地图是否可以实现官方示例中的格点图

### ISSUE THREAD

**Issue by shaxiu** [plainheart/echarts-extension-amap#49]
### 问题描述
高德地图是否可以实现[echarts官网的格点图效果](https://echarts.apache.org/examples/zh/editor.html?c=map-bin)
我用百度地图实现的时候遇到了东西半球数据分开渲染的情况，每次只能展示东半球的或西半球的数据，不清楚如何解决
### 效果展示
在线demo地址：https://codepen.io/coderxiu/pen/xxMGYod
![image](https://github.com/plainheart/echarts-extension-amap/assets/57855264/8e2ebe68-cda0-4a65-b63c-76debfdefaf1)
![image](https://github.com/plainheart/echarts-extension-amap/assets/57855264/f1d1e6cb-17ee-4572-8f72-185bec9c3f56)

**Comment by plainheart** [comment]
大概是百度地图在处理跨半球时有问题。高德地图扩展也支持分箱图示例，只需要把 bmap 相关代码替换为 amap 即可，这里是一个基于你提供的代码简单修改后的例子。https://codepen.io/plainheart/pen/bGzVgbz

**Comment by shaxiu** [comment]
可以了，十分感谢！！！
