### ISSUE TITLE
当我在用鼠标滚轮缩小或者放大地图时，并不会从我鼠标的地方放大或者缩小，而是整体向上移动

### ISSUE THREAD

**Issue by 530209190** [plainheart/echarts-extension-amap#5]

**Comment by 530209190** [comment]
高德地图版本2.0 如用1.4.15 无此问题
刚初始化加载完毕
![image](https://user-images.githubusercontent.com/44056185/81787338-765e8c80-9533-11ea-825c-cb0368e0409a.png)
使用鼠标滚轮缩小后
![image](https://user-images.githubusercontent.com/44056185/81787351-7bbbd700-9533-11ea-9a44-e234942b3101.png)
继续缩小。
![image](https://user-images.githubusercontent.com/44056185/81787358-7e1e3100-9533-11ea-9c9d-4bf22266eea8.png)

**Comment by 530209190** [comment]
加载完毕时
![微信图片_20200513160621](https://user-images.githubusercontent.com/44056185/81787520-c4739000-9533-11ea-9e5b-690d5490c007.png)
当我使用鼠标滚轮缩小后。
![微信图片_20200513160632](https://user-images.githubusercontent.com/44056185/81787581-d81ef680-9533-11ea-80bc-e184da0f06bf.png)
继续缩小。
![微信图片_20200513160637](https://user-images.githubusercontent.com/44056185/81787598-df460480-9533-11ea-8389-5587282e1d6f.png)

**Comment by 530209190** [comment]
就单单使用了鼠标滚轮。  鼠标并没有移动。
但是我在使用您提供的示例时，并没有出现此问题

**Comment by plainheart** [comment]
@530209190 你现在用的是插件版本是最新的吗？如果是我稍后测试下。感谢反馈！

**Comment by plainheart** [comment]
如果可以，最好麻烦你贴出一下可复现的代码示例。

**Comment by 530209190** [comment]
用的是1.1.1，从npm上拉下来的代码。

**Comment by 530209190** [comment]
代码github上传不了= = 我发你邮箱了。。。

**Comment by plainheart** [comment]
@530209190 好的 收到 确定原因了会再回复你。

**Comment by plainheart** [comment]
已经使用了与你所发的示例相近的代码（除了未使用Vue.js），但很遗憾没能复现。
鼠标滚轮缩放 向上移动 很大可能是center没设置好
难道是被哪里修改了？毕竟有使用Vue。

```js
var option = {
  title: {
    text: '地图测试',
    left: 'center'
  },
  tooltip: {
    trigger: 'item'
  },
  amap: {
    center: [104.114129, 37.550339],
    zoom: 3,
    roam: true
  },
  series: [{
    type: 'effectScatter',
    coordinateSystem: 'amap',
    data: convertData(data),
    encode: {
      value: 2
    },
    markPoint: {
      symbolSize: 2
    },
    showEffectOn: 'render',
    rippleEffect: {
      brushType: 'stroke'
    },
    hoverAnimation: true,
    label: {
      formatter: '{b}',
      position: 'right',
      show: true
    },
    itemStyle: {
      color: 'yellowgreen',
      shadowBlur: 10,
      shadowColor: '#333'
    },
    zlevel: 1
  }]
};
// initialize echart
var chart = echarts.init(document.getElementById("echarts-amap"));
chart.setOption(option);
// get amap instance
var amap = chart.getModel().getComponent("amap").getAMap();
amap.on('zoomend', function (ev) {
  const zoom = amap.getZoom()
  // 此处 是缩放等级小于某一等级会显示标签名字，否则不显示。
  if (zoom >= 10) {
    if (!option.series[0].label.show) {
      const center = amap.getCenter();
      option.series[0].label.show = true;
      option.amap.zoom = zoom;
      option.amap.center = [center.lng, center.lat];
      chart.setOption(option);
    }
  } else {
    if (option.series[0].label.show) {
      const center = amap.getCenter();
      option.series[0].label.show = false;
      option.amap.zoom = zoom;
      option.amap.center = [center.lng, center.lat];
      chart.setOption(option);
    }
  }
});
```

**Comment by 530209190** [comment]
我觉得应该是与vue有关，因为截图上我使用了您提供的example代码，也出现同样的问题。

**Comment by 530209190** [comment]
谢谢您，

**Comment by plainheart** [comment]
好的 其实也不一定 我会再跟踪下 issue先不用关

**Comment by plainheart** [comment]
现在能确认不是Vue所导致的问题 似乎是由于容器的`overflow: hidden`引起的
```js
html, body, #echarts-amap {
        width: 100%;
        height: 100%;
        overflow: hidden;
}
```
如果我们去掉`overflow: hidden`则不会出现这个问题，我给的示例中正好没有加，所以没能复现。
本质原因还得继续寻找，如果你对这个有什么想法可以提出来讨论下。

**Comment by plainheart** [comment]
暂时加了一个hack，判断高德地图API是2.0版本的时候，给echarts容器DOM元素的`oveflow`强制设置为`auto`了，临时可以解决问题。
在`CustomLayer`上，2.0新版API较之于1.4.15版本有所不同，创建的DOM结构也有所不同，不知道这些跟`overflow`有什么具体的关系，反正加了这个hack后暂时不会出现你说的这个问题了，稍后我发一版新的（1.2.0），到时麻烦你再升级下试试。

**Comment by 530209190** [comment]
升级了，已经没问题了，谢谢啦。

**Comment by plainheart** [comment]
经测试，当前的高德地图似乎已不存在此问题，插件的新版本 [1.7.0](https://github.com/plainheart/echarts-extension-amap/releases/tag/v1.7.0) 也已去除 hack 代码，故暂且关闭。
