### ISSUE TITLE
高德地图版本判断方式有误

### ISSUE THREAD

**Issue by LP1996** [plainheart/echarts-extension-amap#51]
最新高德地图使用 v 字段标识版本，isAMap2X 函数可能存在问题，version 在多次加载时会被覆写

版本标识：
![image](https://github.com/plainheart/echarts-extension-amap/assets/26558905/f71532d5-7e42-4e6a-8c82-197c6657690c)

version 被覆写：
![image](https://github.com/plainheart/echarts-extension-amap/assets/26558905/32fd8b4c-10d9-4290-923a-8c518bb045fc)

**Comment by plainheart** [comment]
感谢反馈。`AMap.version` 在高德地图 2.0 版本即为 `AMap.v`，根据你的信息才知道在 1.x 版本，`AMap.version` 也是有可能存在的。稍后会修复下。

**Comment by plainheart** [comment]
已修复，抽空可以帮忙检验下是否问题仍然存在。
