### ISSUE TITLE
在高德地图上添加了maker 但是给maker添加点击事件后 并不会正确触发

### ISSUE THREAD

**Issue by ysqluck** [plainheart/echarts-extension-amap#6]
![image](https://user-images.githubusercontent.com/53855691/81829974-1507df00-956e-11ea-97e1-a8c3e9488e73.png)
进入页面后会直接打印出来（在没有点击的时候）
![image](https://user-images.githubusercontent.com/53855691/81830097-3e286f80-956e-11ea-94f7-e8aca3ddc127.png)
点击不到maker我的理解是 视图的最上层是echarts的图层 点击不到geo
但是如何正确添加点击穿透？css  pointer-events: none？
但是为啥 一进页面没有点击  缺还是打印出来了-。-  
求解

**Comment by plainheart** [comment]
嗯 你说的我理解 由于echarts是通过高德地图CustomLayer实现的 覆盖在高德地图上 可能会出现无法点击marker的问题 你可以通过调整echartsLayer的zIndex解决问题
第一种方案是设定option的时候就指定一个比较小的zIndex 这里假定100 不一定可以
```js
option = {
  amap: {
    ...,
    echartsLayerZIndex: 100
  }
}
```
第二种是获取到echartsLayer实例，调用其setzIndex方法设置
```js
var echartsLayer = chart
  .getModel()
  .getComponent("amap")
  .getAMap()
  .getEchartsLayer();
// 参考https://lbs.amap.com/api/javascript-api/reference/self-own-layers#customlayer
echartsLayer.setzIndex(100);
```

**Comment by plainheart** [comment]
试了一下 高德地图的maker覆盖物图层的zIndex是120，设置一个小于120的差不多就行。

**Comment by plainheart** [comment]
对于你说的未点击marker就打印的问题 我这里没能复现 点击了才会触发。

**Comment by ysqluck** [comment]
辛苦了辛苦了 问题解决了

**Comment by plainheart** [comment]
@ysqluck 兄弟这么晚还在加班 也是辛苦了 😄

**Comment by ysqluck** [comment]
主要你的插件给力 要不是 真是写不出来

**Comment by plainheart** [comment]
还遗留一些Bug 高德地图比百度地图难适配 还得继续折腾。

**Comment by ysqluck** [comment]
加油  我这边会帮你推荐推荐  只能star相助了 哈哈

**Comment by plainheart** [comment]
好的 在此先谢 要是没其他问题 这个issue就先关闭了哈

**Comment by ysqluck** [comment]
ok

**Comment by ysq352358871** [comment]
我遇到了同样的问题，但是设置层级没效果

**Comment by ysq352358871** [comment]
我遇到了同样对的问题，但是设置层级没效果
