### ISSUE TITLE
旋转 echarts 不会自动更新

### ISSUE THREAD

**Issue by YeeMarco** [plainheart/echarts-extension-amap#7]
旋转地图或者切换地图视角的时候，echarts其它系列的点不会自动更新。mapmove,zoom之类的可以自动更新。
=========================================

**Comment by plainheart** [comment]
当前只处理了mapmove、zoom这些事件，地图旋转或者视角切换似乎也没事件可触发，暂时可以在代码里手动调用`chart.resize()`手动更新下。

**Comment by YeeMarco** [comment]
对的，我一开始也找了半天的事件，后面发现 拖拽事件，也是可以用在3dmode 的地图上的，好像可以实现。

**Comment by plainheart** [comment]
拖拽是可以的 但是如果用 `setPitch` 似乎就无法监听了

**Comment by YeeMarco** [comment]
手动调用chart.resize()手动更新，可以实现
