### ISSUE TITLE
如何跟随地图重绘？

### ISSUE THREAD

**Issue by ghost** [plainheart/echarts-extension-amap#9]
![image](https://user-images.githubusercontent.com/57943525/88265392-ff4a2f00-ccff-11ea-89e7-717e65944357.png)

如图  在拖动过程中做了防抖处理  当拖动未结束就不重新渲染 但这个效果不怎么好看啊

在  echarts-amap 中实现了

 var layer = echart
        .getModel()
        .getComponent('amap')
        .getLayer()
layer.render = function() {
        echart.setOption({ series })
      }
监听图层的渲染 使echarts跟随其渲染，

**Comment by plainheart** [comment]
你使用的是 echarts-amap 还是 echarts-extension-amap ?

**Comment by 1449281827** [comment]
目前使用的是echarts-amap 但是不兼容2.0的api， 准备更换 echarts-extension-amap。 看到您的实例中  拖动中不会跟随地图重绘。而是在防抖后执行一次重绘

**Comment by 1449281827** [comment]
上面的代码是在  echarts-amap 中实现的， 如何 在echarts-extension-amap实现跟随地图重绘的效果？

**Comment by plainheart** [comment]
我在 [README](https://github.com/plainheart/echarts-extension-amap/blob/master/README.zh-CN.md) 里边提供的有个示例，不过也会有一定延迟，不想要延迟可以把 animation 设置为 false。

**Comment by plainheart** [comment]
使用即将发布的 echarts 5.0，以及本扩展插件的最新版本 1.6.0 可以实现跟地图重绘，待echarts 5.0 正式版发布后可以尝试一下。
